name: Build advisor-fund database

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 8 * *'


jobs:
  run-python-script:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install beautifulsoup4
          pip install requests
          pip install pandas
          pip install numpy
          pip install openpyxl
          pip install futures
      
      - name: Run Python script
        run: python -u python/02_scrape_iapd.py
      
      - name: Add database file and commit	
        run: |
          git add .	
          git config user.name "Automated"	
          git config user.email "actions@users.noreply.github.com"	
          git commit -m "Update advisor-fund database" 	
          
      - name: Push CRDs
        run: git push
