name: Pull CRDs

on: workflow_dispatch
#  schedule:
#    - cron: '0 0 6 * *'


jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: automation

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run Python script
        run: python python/01_pull_crds.py
