name: Pull CRDs

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 6 * *'


jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install beautifulsoup4
          pip install requests
          pip install pandas
          pip install numpy
          pip install openpyxl
          pip install requests-random-user-agent
      
      - name: Run Python script
        run: python -u python/01_pull_crds.py
      
      - name: Add CRD file and commit	
        run: |
          git add .	
          git config user.name "Automated"	
          git config user.email "actions@users.noreply.github.com"	
          git commit -m "Latest CRDs" 	
          
      - name: Push CRDs
        run: git push
